STUDY_CONFIG = {
    "Relative Rotation Graph": "rrg_study",
    "Market Wide": "market_wide_study",
    "Value Investment": "value_investment_study",
    "Market Pricing": "market_pricing_study",
    "Fundamental Pricing": "fundamental_pricing_study",
    "Momentum top down": "momentum_top_study",
    "ETF Flow": "etf_flow_study",
    "ETF Structure": "etf_structure_study",
    "Magic Fomula": "magic_fomula_study",
    "Stock Events": "stock_events_study",
    "Stock Dividend": "stock_dividend_study",
    "Stock Split": "stock_split_study",
    "Stock Issue": "stock_issue_study",
    "Bank Pricing": "bank_pricing_study",
    "Steven Fomula": "steven_fomula_study",
    "Relative Comparsion": "relative_comparsion_study",
    "Stock Foregin Flow": "stock_foregin_flow_study",
    "Stock Liqudity Flow": "stock_liqudity_flow_study",
    "Stock Factors Models": "stock_factors_models_study",
    "Stock Factor Base": "stock_factor_base_study",
    "Stock Factors Value": "stock_factors_value_study",
    "Stock Factors Size": "stock_factors_size_study",
    "Stock Factors Quality": "stock_factors_quality_study",
    "Stock Factors Momentum": "stock_factors_momentum_study",
    "Stock Factors Volatility": "stock_factors_volatility_study",
    "Stock Financial Report": "stock_financial_report_study",
    "Stock Earning Suprise": "stock_earning_suprise_study",
    "Stock Financial Momentum": "stock_financial_momentum_study",
    "Cash Flow": "cash_flow_study",
    "Stock News Momentum": "stock_news_momentum_study",
    "Stock Headline Momentum": "stock_headline_momentum_study",
    "Relative Strength Compasion": "relative_stregth_compasion_study",
    "Stock Overnight": "stock_overnight_study",
    "Stock Gaps Recover": "stock_gaps_recover_study",
    "VN30F Gaps Recover": "vn30f_gaps_recover_study",
    "VN30F Gaps Dips": "vn30f_gaps_dips_study",
    "VN30F Foregin Flow": "vn30f_foregin_flow",
    "VN30 Hedging Flow": "vn30_hedging_flow",
    "VN30 Cash Flow": "vn_30_cash_flow_study",
    "VN30 Volality": "vn30_volality_study",
    "Stock Intraday": "stock_intraday_study",
    "RS Momentum": "rs_momentum_study",
    "Market Value": "market_value_study",
    "Stock Blind Order": "stock_blind_order",
    "Stock Cancel Order": "stock_cacnel_order",
    "Warrants Blind Order": "warrants_blind_order_study",
    "Warrants Simmulation": "warrants_simmulation_study",
    "Warrants expexted value": "warrants_exp_value_study",
    "Warrants History": "warrants_history_study",
    "Warrants Gap Recover": "warrants_gap_recover_study",
    "Warrants Volatility": "warrants_volatility_study",
    "Stock Low Flow": "stock_low_flow_study",
    "Stock 123 Pullback": "stock_123_pullback_study",
    "Stock Darvas Box": "stock_darvas_box_study",
    "Stock TET": "stock_tet_study",
    "TCBS Agent": "tcbs_agent_study",
    "TCBS Market Calendar": "tcbs_market_calendar_study",
    "TCBS Stock Noti": "tcbs_stock_noti_study",
    "Stock Fear Zone": "stock_fear_zone_study",
    "Stock DCF": "stock_dcf_study",
    "Stock Evaluation": "stock_evaluation_study",
    "Stock Income Statement": "stock_income_statement_study",
    "Stock Growth": "stock_growth_study",
    "Scraping BBSR": "scraping_bbsr_study",
    "Stock Fib Zone": "stock_fib_zone_study",
    "Fibo Retracement": "fibo_retracement_study",
    "Stock Value Cluster": "stock_cluster_value_study",
    "Stock Price Cluster": "stock_cluster_price_study",
    "Stock Industry Cluster": "stock_cluster_industry_study",
    "VN30 Liquidity": "vn30_liquidity_study",
    "Stock Summulation": "stock_summulation_study",
    "Stock Cycle": "stock_cycle_study"
}
