STUDY_CONFIG = {
    "rrg_study": "Relative Rotation Graph",
    "market_wide_study": "Market Wide",
    "value_investment_study": "Value Investment",
    "market_pricing_study": "Market Pricing",
    "fundamental_pricing_study": "Fundamental Pricing",
    "momentum_top_study": "Momentum top down",
    "etf_flow_study": "ETF Flow",
    "etf_structure_study": "ETF Structure",
    "magic_fomula_study": "Magic Fomula",
    "stock_events_study": "Stock Events",
    "stock_dividend_study": "Stock Dividend",
    "stock_split_study": "Stock Split",
    "stock_issue_study": "Stock Issue",
    "bank_pricing_study": "Bank Pricing",
    "steven_fomula_study": "Steven Fomula",
    "relative_comparsion_study": "Relative Comparsion",
    "stock_foregin_flow_study": "Stock Foregin Flow",
    "stock_liqudity_flow_study": "Stock Liqudity Flow",
    "stock_factors_models_study": "Stock Factors Models",
    "stock_factor_base_study": "Stock Factor Base",
    "stock_factors_value_study": "Stock Factors Value",
    "stock_factors_size_study": "Stock Factors Size",
    "stock_factors_quality_study": "Stock Factors Quality",
    "stock_factors_momentum_study": "Stock Factors Momentum",
    "stock_factors_volatility_study": "Stock Factors Volatility",
    "stock_financial_report_study": "Stock Financial Report",
    "stock_earning_suprise_study": "Stock Earning Suprise",
    "stock_financial_momentum_study": "Stock Financial Momentum",
    "cash_flow_study": "Cash Flow",
    "stock_news_momentum_study": "Stock News Momentum",
    "stock_headline_momentum_study": "Stock Headline Momentum",
    "relative_stregth_compasion_study": "Relative Strength Compasion",
    "stock_overnight_study": "Stock Overnight",
    "stock_gaps_recover_study": "Stock Gaps Recover",
    "vn30f_gaps_recover_study": "VN30F Gaps Recover",
    "vn30f_gaps_dips_study": "VN30F Gaps Dips",
    "vn30f_foregin_flow": "VN30F Foregin Flow",
    "vn30_hedging_flow": "VN30 Hedging Flow",
    "vn_30_cash_flow_study": "VN30 Cash Flow",
    "vn30_volality_study": "VN30 Volality",
    "stock_intraday_study": "Stock Intraday",
    "rs_momentum_study": "RS Momentum",
    "market_value_study": "Market Value",
    "stock_blind_order": "Stock Blind Order",
    "stock_cacnel_order": "Stock Cancel Order",
    "warrants_blind_order_study": "Warrants Blind Order",
    "warrants_simmulation_study": "Warrants Simmulation",
    "warrants_exp_value_study": "Warrants expexted value",
    "warrants_history_study": "Warrants History",
    "warrants_gap_recover_study": "Warrants Gap Recover",
    "warrants_volatility_study": "Warrants Volatility",
    "stock_low_flow_study": "Stock Low Flow",
    "stock_123_pullback_study": "Stock 123 Pullback",
    "stock_darvas_box_study": "Stock Darvas Box",
    "stock_tet_study": "Stock TET",
    "tcbs_agent_study": "TCBS Agent",
    "tcbs_market_calendar_study": "TCBS Market Calendar",
    "tcbs_stock_noti_study": "TCBS Stock Noti",
    "stock_fear_zone_study": "Stock Fear Zone",
    "stock_dcf_study": "Stock DCF",
    "stock_evaluation_study": "Stock Evaluation",
    "stock_income_statement_study": "Stock Income Statement",
    "stock_growth_study": "Stock Growth",
    "scraping_bbsr_study": "Scraping BBSR",
    "stock_fib_zone_study": "Stock Fib Zone",
    "fibo_retracement_study": "Fibo Retracement",
    "stock_cluster_value_study": "Stock Value Cluster",
    "stock_cluster_price_study": "Stock Price Cluster",
    "stock_cluster_industry_study": "Stock Industry Cluster",
    "vn30_liquidity_study": "VN30 Liquidity",
    "stock_summulation_study": "Stock Summulation",
    "stock_cycle_study": "Stock Cycle",
    "stock_hedging_study": "Stock Hedging",
    "stock_candle_stick_study": "Stock Candles",
    "stock_lvm_study": "Stock LVM",
    "stock_momentum_study": "Stock Momentum",
    "momentum_top_2_study": "Momentum Top 2",
    "momentum_top_1_study": "Momentum Top 1",
    "stock_llr_top_study": "Stock LLR Top",
    "stock_liquidity_lock_study": "Stock Liquidity Lock",
    "stock_liquidity_lock2_study": "Stock Liquidity Lock 2",
    "stock_liquidity_lock3_study": "Stock Liquidity Lock 3",
    "stock_liquidity_lock4_study": "Stock Liquidity Lock 4",
    "stock_liquidity_lock5_study": "Stock Liquidity Lock 5",
    "stock_liquidity_lock6_study": "Stock Liquidity Lock 6",
    "stock_liquidity_lock7_study": "Stock Liquidity Lock 7",
}
